apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
imageRepository: docker.io/kubernetes1122
kubernetesVersion: v1.12.2
networking:
  dnsDomain: cluster.local
  podSubnet: "10.244.0.0/16"
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: JoinConfiguration
apiEndpoint:
  advertiseAddress: 192.168.137.238
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    pod-infra-container-image: docker.io/kubernetes1122/pause:3.1
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    pod-infra-container-image: docker.io/kubernetes1122/pause:3.1
discoveryToken: abcdef.0123456789abcdef
tlsBootstrapToken: abcdef.0123456789abcdef
token: abcdef.0123456789abcdef
---